charts/keep/templates/backend-hpa.yaml
charts/keep/templates/backend-ingress.yaml
charts/keep/templates/backend-route.yaml
charts/keep/templates/frontend-hpa.yaml
charts/keep/templates/frontend-ingress.yaml
charts/keep/templates/frontend-route.yaml
charts/keep/templates/keep-backend-service.yaml
charts/keep/templates/keep-backend.yaml
charts/keep/templates/keep-db-pv.yaml
charts/keep/templates/keep-db-pvc.yaml
charts/keep/templates/keep-db-service.yaml
charts/keep/templates/keep-db.yaml
charts/keep/templates/keep-frontend-service.yaml
charts/keep/templates/keep-frontend.yaml
charts/keep/templates/keep-websocket-server-service.yaml
charts/keep/templates/keep-websocket-server.yaml

Closes #5 
Added if statements to chart's components, including sub components to prevent them from being installed if root component is disabled. 
This may not be the best way to go about this (individual if statements on each file for a component), but it does work and illustrates the issue with #5 at the worst

Enforce root component's enabled value

---

charts/keep/templates/backend-hpa.yaml
charts/keep/templates/frontend-hpa.yaml
ct.yaml

Closes #8 
fixed hpa target ref names.

fix: hpa target refs

---

charts/keep/Chart.yaml

fix: update chart.yaml

---

charts/keep/Chart.yaml
charts/keep/templates/keep-backend.yaml
charts/keep/templates/keep-db.yaml
charts/keep/templates/keep-frontend.yaml
charts/keep/templates/keep-websocket-server.yaml

fix: add keep-component label to deployments

---

charts/keep/Chart.yaml
charts/keep/templates/ingress.yaml
charts/keep/values.yaml

close https://github.com/keephq/helm-charts/issues/67

feat: allow classType

---

charts/keep/Chart.yaml

close https://github.com/keephq/helm-charts/issues/81

feat: release 0.1.43

---

charts/keep/Chart.yaml
charts/keep/templates/db-pvc.yaml
charts/keep/values.yaml

close https://github.com/keephq/helm-charts/issues/83

feat: retain pvc

---

charts/keep/Chart.yaml

close https://github.com/keephq/helm-charts/issues/88

feat: release 0.1.47

---

charts/keep/Chart.yaml

close https://github.com/keephq/helm-charts/issues/96

feat: 0.1.52

---

charts/keep/Chart.yaml

close https://github.com/keephq/helm-charts/issues/102

feat(release): 0.1.55

---

charts/keep/Chart.yaml
charts/keep/templates/_helpers.tpl
local_test_nginx.sh

close https://github.com/keephq/helm-charts/issues/103

fix: adjust keep api url

---

charts/keep/Chart.yaml
charts/keep/templates/backend.yaml

fix(backend): environment variable database name

---

.github/workflows/release.yml

Generate release notes to use in the GitHub release.  This helps tools like Renovate/Dependabot to provide a clear context on what an update provides.

ci: generate release notes on release

---

charts/keep/Chart.yaml

close https://github.com/keephq/helm-charts/issues/124

feat: release 0.1.62 (with Keep 0.35.13)

---

charts/keep/Chart.yaml
charts/keep/templates/delete-secret-job.yaml
charts/keep/values.yaml

close https://github.com/keephq/helm-charts/issues/129

feat: add delete image customize

---

charts/keep/Chart.yaml
charts/keep/README.md
charts/keep/templates/db-cleanup-cronjob.yaml

Fixes image after addition of postgres for mysql clean-up job

fix: update MySQL cleanup job image reference

---

charts/keep/Chart.yaml
charts/keep/templates/backend-provision.yaml
charts/keep/templates/backend.yaml
charts/keep/templates/provision.yaml
charts/keep/values.yaml

Closes #141
Introduce new configuration options for backend provisioning, allowing users to define providers and workflows in the Helm chart.

feat(helm): add support for providers and workflows provisioning

---

charts/keep/Chart.yaml

feat: bump version to 0.40.3

---

charts/keep/Chart.yaml
charts/keep/templates/backend.yaml

Fixes the conditional check to include provision providers in environment variable configuration.

fix: add missing envFrom for provision providers

---

charts/keep/Chart.yaml

chore: update version to 0.1.80 (0.41.8)
